export enum bucketActions {
    DELETE_ITEM = "DELETE_ITEM",
    DELETE_ALL = "DELETE_ALLDELETE_ALL",
    FAVORITE_ITEM = "FAVORITE_ITEM",
    SET_ITEM_LOADING = "SET_ITEM_LOADING",
    SET_ITEM_ERROR = "SET_ITEM_ERROR",
    SET_ITEMS = "SET_ITEMS",
    ADD_ITEM = "ADD_ITEM",
}